### ISSUE TITLE
documentation on hep2?

### ISSUE THREAD

**Issue by clintberry** [sipcapture/HEP#3]
I have a parser written in Go that I will be putting in its own repo soon. I support hep v1 and hep v3 but I can't find docs on hep v2. Do they exist anywhere?

**Comment by clintberry** [comment]
Oh sweet! https://github.com/sipcapture/hep-go

And you gave us props! thanks! We are improving this now. I'll submit a pull request when we are ready.

**Comment by lmangani** [comment]
Thanks Clint, much appreciated and welcome! we'd be glad to provide access to push to the hep-go repository and cooperate extending to support encoding too and the full protocol scope

**Comment by adubovikov** [comment]
@clintberry 

hepv2 is just extension of hepv1 including timestamps and capture id:

https://github.com/sipcapture/hep-c/blob/master/core_hep.h#L189
https://github.com/sipcapture/hep-c/blob/master/core_hep.h#L198

hepv1 = hep_hdr (hep_hdr.hp_v = 1)
hepv2 = concat(hep_hdr + hep_timehdr)  (hep_hdr.hp_v = 2)

**Comment by clintberry** [comment]
oh nice. easy peasy. Pull request coming with some basic code cleanup and comments and such. That dependency on the sip parser sucks... I wonder if we should leave that up to the person implementing...
